"""Writes sw-manifest.js: the file lists + versions the service worker (sw.js)
uses to make the site work offline.

    python tools/build_offline_manifest.py

Re-run it after adding, removing or changing site files, then deploy. Browsers
re-check sw-manifest.js on every visit, so a changed file list or changed file
contents makes them pick up the new version automatically.

  CORE   - saved on the first visit (the main page and every light project)
  HEAVY  - big game builds and songs, saved the first time they are used or
           all at once via "Save everything for offline" on the main page
"""
import glob
import hashlib
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'sw-manifest.js')

CORE = [
    'index.html', 'page2.html', 'offline.html', 'site.json', 'functions_to_work.json', 'tiles.json',
    'pixel-transition.js', 'site-nav.js', 'offline.js', 'ambient.js', 'daily.js', 'miniplayer.js', 'collage-fun.js',
    'images_to_use/optimized/*',
    'images_to_use/bg_sequence_*/*_used.webp',
    'images_to_use/tiles_texture_pixel.png', 'images_to_use/puzzle_thumb.webp',
    'images_to_use/page1_btn_image.webp', 'images_to_use/page2_btn_image.webp',
    'images_to_use/beard*.webp', 'images_to_use/glasses.webp',
    'popup_random_images/*',
    'projects/0[1-5]/images/0.webp',
    'projects/03/index.html', 'projects/03/images/f1_pitstop.jpg',
    'projects/04/index.html', 'projects/04/playlist.js', 'projects/04/ps_player_images/*', 'projects/04/music/cover/*',
    'projects/05/index.html', 'projects/05/windows98.html', 'projects/05/paint.html', 'projects/05/page_images/*',
]

HEAVY = [
    'projects/01/index*',
    'projects/02/index.html', 'projects/02/Build/*', 'projects/02/TemplateData/*', 'projects/02/StreamingAssets/*',
    'projects/04/music/*.mp3',
]

# Google Fonts stylesheets the pages use (their font files are cached too)
FONT_CSS = [
    'https://fonts.googleapis.com/css2?family=Kalam:wght@400;700&family=Oswald:wght@600;700&display=swap',
    'https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap',
    'https://fonts.googleapis.com/css2?family=VT323&display=swap',
]


def expand(patterns):
    files = []
    for pat in patterns:
        hits = sorted(glob.glob(os.path.join(ROOT, pat)))
        if not hits:
            raise SystemExit('pattern matched nothing: ' + pat)
        files += [h for h in hits if os.path.isfile(h)]
    seen, out = set(), []
    for f in files:
        rel = os.path.relpath(f, ROOT).replace(os.sep, '/')
        if rel not in seen:
            seen.add(rel)
            out.append(rel)
    return out


def file_hash(rel):
    h = hashlib.sha1()
    with open(os.path.join(ROOT, rel), 'rb') as f:
        for chunk in iter(lambda: f.read(1 << 20), b''):
            h.update(chunk)
    return h.hexdigest()[:12]


def url(rel):
    # plain relative paths; sw.js resolves and normalises them (canon())
    return rel


def main():
    core = expand(CORE)
    heavy = [f for f in expand(HEAVY) if f not in core]
    core_hashes = {url(f): file_hash(f) for f in core}
    heavy_hashes = {url(f): file_hash(f) for f in heavy}
    version = hashlib.sha1(json.dumps([core_hashes, FONT_CSS], sort_keys=True).encode()).hexdigest()[:10]
    size = lambda files: sum(os.path.getsize(os.path.join(ROOT, f)) for f in files)

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('// Generated by tools/build_offline_manifest.py - do not edit by hand.\n')
        f.write('self.OFFLINE_VERSION = %s;\n' % json.dumps(version))
        f.write('self.OFFLINE_CORE = %s;\n' % json.dumps(core_hashes, indent=1))
        f.write('self.OFFLINE_HEAVY = %s;\n' % json.dumps(heavy_hashes, indent=1))
        f.write('self.OFFLINE_HEAVY_BYTES = %d;\n' % size(heavy))
        f.write('self.OFFLINE_FONT_CSS = %s;\n' % json.dumps(FONT_CSS, indent=1))
    print('core : %3d files %6.1f MB' % (len(core), size(core) / 1e6))
    print('heavy: %3d files %6.1f MB' % (len(heavy), size(heavy) / 1e6))
    print('version', version, '->', os.path.relpath(OUT, ROOT))


if __name__ == '__main__':
    main()
